spring.application.name: stream-consumer

spring:
  kafka:
    streams:
      client-id: theconsumer
      properties:
        default.key.serde: org.apache.kafka.common.serialization.StringDeserializer
        default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
        spring.json.trusted.packages: "*"
      replication-factor: 1
    bootstrap-servers: localhost:29092